export default {
    FETCH_VEHICLES: 'FETCH_VEHICLES',
    FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
    FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_FAILURE',

    FETCH_PLANETS: 'FETCH_PLANETS',
    FETCH_PLANETS_SUCCESS: 'FETCH_PLANETS_SUCCESS',
    FETCH_PLANETS_FAILURE: 'FETCH_PLANETS_FAILURE',

    FETCH_RESULTS: 'FETCH_RESULTS',
    FETCH_RESULTS_SUCCESS: 'FETCH_RESULTS_SUCCESS',
    FETCH_RESULTS_FAILURE: 'FETCH_RESULTS_FAILURE',

    UPDATE_SELECTED_VALUES: 'UPDATE_SELECTED_VALUES',

    RESET_SELECTED_VALUES: 'RESET_SELECTED_VALUES',



    UPDATE_VEHICLES_COUNT: 'UPDATE_VEHICLES_COUNT',
}